### ISSUE TITLE
Subject identification fields doesn't show up in response

### ISSUE THREAD

**Issue by weiglszonja** [brainstem-org/brainstem_python_api_tools#5]
I created a subject for testing the relations of tables, it looks like this:

<img width="497" alt="Screenshot 2023-05-10 at 14 15 03" src="https://github.com/brainstem-org/brainstem_python_api_tools/assets/24475788/9e1b5e16-5dec-48a2-ba0d-0fe2889aa014">

I noticed that even though ear tag, cage id, and source was specified, it doesn't show up in the response:
https://www.brainstem.org/rest/private/stem/subject
```json
{
  "subjects": [
    {
      "id": "d07a3e34-72b4-40d7-8fed-d1610f235353",
      "name": "TestS1",
      "description": "<p>asd</p>",
      "strain": "a8c28e25-7d15-4112-b3c6-031cbe4ee4f1",
      "sex": "F",
      "genetic_line": "",
      "projects": [
        "0040392a-79a1-4653-902c-4f9e5f5ecb9d"
      ],
      "birth_date": "2023-03-01",
      "death_date": null,
      "extra_content_json": [],
      "actions": [
        "c649b1be-662e-46ee-97b7-506ffb922a82"
      ],
      "subjectstatechanges": [],
      "tags": [],
      "links": {
        "projects": "projects/",
        "actions": "actions/"
      }
    }
  ]
}
```
I'm not sure this is intentional, also, if I change the subject, any fields that were in `"extra_content_json"` disappears.

Feel free to close or move this issue to a more suited place if you like.

**Comment by petersenpeter** [comment]
Hi 

ear tag, cage id, and the source were not added to the API by mistake. Will be fixed. 

I tested the other issue with the extra_content_json field, and I see the content. Make sure to set the extra content type as _array_. The other _custom_ option was there for testing purposes and will be removed in the future. 

/ Peter
